/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author aamrah
 */
public class CommunityDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityDataJPanel
     */
    City city;
    PersonDirectory personDir;
    PatientDirectory patientDir;
    public CommunityDataJPanel(City city, PersonDirectory personDir, PatientDirectory patientDir) {
        initComponents();
        this.city=city;
        this.personDir= personDir;
        this.patientDir=patientDir;
        loadCommunityList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCommunitydata = new javax.swing.JLabel();
        lblHowmany = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        lblCases = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        communityList = new javax.swing.JTable();

        lblCommunitydata.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblCommunitydata.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunitydata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCommunitydata.setText("Community Data");

        lblHowmany.setForeground(new java.awt.Color(255, 255, 255));
        lblHowmany.setText("Choose a community you want to check the total number of abnormal BP cases : ");

        btnCalculate.setText("Calculate cases");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblCases.setForeground(new java.awt.Color(255, 255, 255));
        lblCases.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCases.setText("0");

        communityList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Community"
            }
        ));
        jScrollPane2.setViewportView(communityList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblCommunitydata, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblHowmany)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCommunitydata, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblHowmany)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculate)
                        .addGap(18, 18, 18)
                        .addComponent(lblCases))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JTable communityList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCases;
    private javax.swing.JLabel lblCommunitydata;
    private javax.swing.JLabel lblHowmany;
    // End of variables declaration//GEN-END:variables

    private void loadCommunityList() {
        DefaultTableModel md=(DefaultTableModel)communityList.getModel();
        md.setRowCount(0);
        Object row[]= new Object[1];
        for(Community c : this.city.getCommunities())
        {  
            row[0]=c.getCommunityName();
            md.addRow(row);
        }
        
        
    }
}
