/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.City;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author aamrah
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    City city;
    PersonDirectory personDir;
    PatientDirectory patientDir;
    
    public MainJFrame() throws FileNotFoundException, IOException {
        initComponents();
        this.city=new City("Boston");
        this.personDir= new PersonDirectory();
        this.patientDir=new PatientDirectory();
       // setPersonDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCommunitydata = new javax.swing.JButton();
        btnPatientdirectory = new javax.swing.JButton();
        btnCreatecommunity = new javax.swing.JButton();
        btnAddhouse = new javax.swing.JButton();
        btnPersondirectory = new javax.swing.JButton();
        btnEncounterhistory = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnCommunitydata.setText("Community Data");
        btnCommunitydata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunitydataActionPerformed(evt);
            }
        });

        btnPatientdirectory.setText("Patient Directory");
        btnPatientdirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientdirectoryActionPerformed(evt);
            }
        });

        btnCreatecommunity.setText("Create a Community");
        btnCreatecommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatecommunityActionPerformed(evt);
            }
        });

        btnAddhouse.setText("Add a House");
        btnAddhouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddhouseActionPerformed(evt);
            }
        });

        btnPersondirectory.setText("Person Directory");
        btnPersondirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersondirectoryActionPerformed(evt);
            }
        });

        btnEncounterhistory.setText("Encounter History");
        btnEncounterhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterhistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCommunitydata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddhouse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatecommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPatientdirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(controlPanelLayout.createSequentialGroup()
                                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPersondirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEncounterhistory))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnCreatecommunity)
                .addGap(45, 45, 45)
                .addComponent(btnAddhouse)
                .addGap(79, 79, 79)
                .addComponent(btnPersondirectory)
                .addGap(62, 62, 62)
                .addComponent(btnPatientdirectory)
                .addGap(65, 65, 65)
                .addComponent(btnEncounterhistory)
                .addGap(75, 75, 75)
                .addComponent(btnCommunitydata)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientdirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientdirectoryActionPerformed
        // TODO add your handling code here:
        PatientDirJPanel patientDire=new PatientDirJPanel(city,personDir,patientDir);
        patientDire.setBackground(Color.pink);
        splitPane.setRightComponent(patientDire);
    }//GEN-LAST:event_btnPatientdirectoryActionPerformed

    private void btnCommunitydataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunitydataActionPerformed
        // TODO add your handling code here:
        CommunityDataJPanel commdata=new CommunityDataJPanel(city,personDir,patientDir);
        commdata.setBackground(Color.pink);
        splitPane.setRightComponent(commdata);
    }//GEN-LAST:event_btnCommunitydataActionPerformed

    private void btnEncounterhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterhistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncounterhistoryActionPerformed

    private void btnAddhouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddhouseActionPerformed
        // TODO add your handling code here:
        AddHouseJPanel addHouse=new AddHouseJPanel(city,personDir,patientDir);
        addHouse.setBackground(Color.pink);
        splitPane.setRightComponent(addHouse);
    }//GEN-LAST:event_btnAddhouseActionPerformed

    private void btnPersondirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersondirectoryActionPerformed
        // TODO add your handling code here:
        PersonDirJPanel personDirectory=new PersonDirJPanel(city,personDir,patientDir);
        personDirectory.setBackground(Color.pink);
        splitPane.setRightComponent(personDirectory);
    }//GEN-LAST:event_btnPersondirectoryActionPerformed

    private void btnCreatecommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatecommunityActionPerformed
        // TODO add your handling code here:
        CommunityJPanel createCommunity=new CommunityJPanel(city,personDir,patientDir);
        createCommunity.setBackground(Color.pink);
        splitPane.setRightComponent(createCommunity);
    }//GEN-LAST:event_btnCreatecommunityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddhouse;
    private javax.swing.JButton btnCommunitydata;
    private javax.swing.JButton btnCreatecommunity;
    private javax.swing.JButton btnEncounterhistory;
    private javax.swing.JButton btnPatientdirectory;
    private javax.swing.JButton btnPersondirectory;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    private void setPersonDirectory()throws FileNotFoundException,IOException{
    
        String str="/Users/aamrah/NetBeansProjects/Assignment4/src/resources/DataFile.txt";
        File file = new File(str);
        
        BufferedReader br= new BufferedReader(new FileReader(file));
 
        // Declaring loop variable
       String st;
        // Holds true till there is nothing to read
        while ((st = br.readLine()) != null){
           String[] s= st.split(",");
           Person p = new Person();
           p.setPersonName(s[0]);
           p.setAddress(s[1]);
           p.setAge(Integer.parseInt(s[2]));
           p.setCity(this.city);
           p.setPincode(s[3]);
           p.setCommunity(s[4]);
           p.setPhone(s[5]);
           //p.setResidence(residence);
           this.personDir.addPersonDir(p);
          
        }    
    }

}

