/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author aamrah
 */
public class CreateJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel1
     */
    Person person;
    int fields=1;
    public CreateJPanel1(Person person) {
        initComponents();
        this.person= person;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bank = new javax.swing.JLabel();
        tlinkedin = new javax.swing.JTextField();
        licenseno = new javax.swing.JLabel();
        tip = new javax.swing.JTextField();
        licenseplate = new javax.swing.JLabel();
        device = new javax.swing.JLabel();
        linkedin = new javax.swing.JLabel();
        tunique = new javax.swing.JTextField();
        ip = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        unique = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        ttel = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        tfax = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        tlat = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        tssn = new javax.swing.JTextField();
        fax = new javax.swing.JLabel();
        tmedical = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        thealth = new javax.swing.JTextField();
        geo = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        tbank = new javax.swing.JTextField();
        tlicenseno = new javax.swing.JTextField();
        medical = new javax.swing.JLabel();
        tlicenseplate = new javax.swing.JTextField();
        health = new javax.swing.JLabel();
        tdevice = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        bio = new javax.swing.JLabel();
        lat = new javax.swing.JLabel();
        lon = new javax.swing.JLabel();
        tlon = new javax.swing.JTextField();
        tmonth = new javax.swing.JTextField();
        tyear = new javax.swing.JTextField();
        btnUploadBio = new javax.swing.JButton();

        bank.setText("Bank account number");

        licenseno.setText("Certificate/license number");

        licenseplate.setText("License Plate Number");

        device.setText("Device identifiers");

        linkedin.setText("LinkedIn");

        ip.setText("Internet protocol address");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        photo.setText("Full face photo");

        unique.setText("Any unique identifying number, characteristic, or cod");

        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        label.setText("Create");

        Name.setText("Name");

        tfax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaxActionPerformed(evt);
            }
        });

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });

        dob.setText("Date of Birth (dd-mm-yyyy)");

        tel.setText("Telephone Number");

        tssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tssnActionPerformed(evt);
            }
        });

        fax.setText("Fax number");

        email.setText("Email ");

        geo.setText("Geographic data");

        ssn.setText("SSN");

        medical.setText("Medical Record Number");

        tlicenseplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlicenseplateActionPerformed(evt);
            }
        });

        health.setText("Health Plan beneficiary number");

        tdevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeviceActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        bio.setText("Biometric (retina scan or fingerprint)");

        lat.setText("Latitude");

        lon.setText("Longitude");

        btnUploadBio.setText("Upload");
        btnUploadBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadBioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(geo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ssn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medical, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(health, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bank, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(licenseno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(licenseplate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(device, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(linkedin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(unique, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ip, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email)
                            .addComponent(photo)
                            .addComponent(bio))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUploadBio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addGap(197, 197, 197))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpload)
                                .addGap(0, 477, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tunique, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                    .addComponent(tssn)
                                    .addComponent(tmedical)
                                    .addComponent(thealth)
                                    .addComponent(tbank)
                                    .addComponent(tlicenseno)
                                    .addComponent(tlicenseplate)
                                    .addComponent(tip)
                                    .addComponent(tfax)
                                    .addComponent(ttel)
                                    .addComponent(tdevice)
                                    .addComponent(tlinkedin)
                                    .addComponent(temail)
                                    .addComponent(tname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tdate, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(tlat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lon)
                                                .addGap(27, 27, 27)
                                                .addComponent(tlon))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(tmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tyear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dob)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geo)
                            .addComponent(tlon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lon))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssn)
                            .addComponent(tssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medical)
                            .addComponent(tmedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(health)
                            .addComponent(thealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bank)
                            .addComponent(tbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseno)
                            .addComponent(tlicenseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseplate)
                            .addComponent(tlicenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(device)
                            .addComponent(tdevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linkedin)
                            .addComponent(tlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ip)
                            .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel)
                            .addComponent(ttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fax)
                            .addComponent(tfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tunique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unique, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(photo)
                            .addComponent(btnUpload))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bio)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSave)
                                    .addComponent(btnUploadBio)))))
                    .addComponent(lat))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        
        if (tname.getText().matches("^([a-zA-Z\\s]+)$"))
        {
            person.setName(tname.getText());
            JOptionPane.showMessageDialog(this, "Name saved" + person.getName());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a name!Please enter a valid name.");
            
        }
       
        if (temail.getText().matches("([a-zA-Z1-9.-_])*(@)([A-Za-z]+)(.com)"))
        {
            person.setEmail(temail.getText());
            JOptionPane.showMessageDialog(this, "Email saved" + person.getEmail());
        }
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not an email!Please enter a valid email.");
            
        }
        String ssn= String.valueOf(Integer.parseInt((tssn.getText())));
        int slen=ssn.length();
        if((Integer.parseInt((tssn.getText())))!=0 && (slen==10))
        {
            person.setSsn(Integer.parseInt((tssn.getText())));
            JOptionPane.showMessageDialog(this, "SSN saved" + person.getSsn());
        }
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not an ssn!Please enter a valid SSN.");
        }
           
        if (tlinkedin.getText().matches("((https://www.linkedin.com/in/)|(www.linkedin.com/in/))([a-zA-Z1-9-_])*/") )
        {
            person.setLinkedin(tlinkedin.getText());
            JOptionPane.showMessageDialog(this, "Linkedin saved" + person.getLinkedin());
        }
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a linkedin address !Please enter a valid address.");
            
        }
        if (tip.getText().matches("(([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}))"))
        {
            person.setIp(tip.getText());
            JOptionPane.showMessageDialog(this, "IP saved" + person.getIp());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not an IP Address!Please enter a valid IP.");
            
        }
        if (Long.parseLong((tbank.getText()))!=0L)
        {
            person.setBank(Long.parseLong(tbank.getText()));
            JOptionPane.showMessageDialog(this, "Bank account saved" + person.getBank());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a bank account!Please enter a valid Bank Account Number!.");
            
        }
        long tel=Long.parseLong((ttel.getText()));
        String strtel=ttel.getText();
        int tlen=strtel.length();
        if (tel!=0L && tlen==10)
        {
            person.setTelephone(tel);
            JOptionPane.showMessageDialog(this, "Telephone number saved" + person.getTelephone());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a phone number!Please enter a valid Telephone Number!.");
            
        }
        long fax=Long.parseLong((tfax.getText()));
        String strfax=tfax.getText();
        int faxlen =strfax.length();
        if (fax!=0L && faxlen==10)
        {
            person.setFAX(fax);
            JOptionPane.showMessageDialog(this, "Fax number saved" + person.getFAX());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a fax number!Please enter a valid FAX Number!.");
            
        }
        if (tlicenseplate.getText().matches("(([a-zA-Z]{1,3})(\\s|-){0,1}([a-zA-Z]{0,2})(\\s|-)([0-9]{1,4}))"))
        {
            person.setLicensePlate(tlicenseplate.getText());
            JOptionPane.showMessageDialog(this, "License plate saved" + person.getLicensePlate());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a license plate!Please enter a valid license plate.");
            
        }
        if (tlicenseno.getText().matches("([a-zA-Z0-9]*)"))
        {
            person.setLicenseNo(tlicenseno.getText());
            JOptionPane.showMessageDialog(this, "License number saved" + person.getLicenseNo());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a license number!Please enter a valid license number.");
            
        }
        if (tdevice.getText().matches("([a-zA-Z0-9]*)"))
        {
            person.setDevice(tdevice.getText());
            JOptionPane.showMessageDialog(this, "Device number saved" + person.getDevice());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a device number!Please enter a valid device number.");
            
        }
        if (tunique.getText().matches("^([a-zA-Z\\s]+)$"))
        {
            person.setUnique(tunique.getText());
            JOptionPane.showMessageDialog(this, "Unique Identifier saved" + person.getUnique());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a unique identifier!Please enter a valid unique identifier.");
            
        }
        long med=Long.parseLong((tmedical.getText()));
        if (med!=0L)
        {
            person.setMedical(med);
            JOptionPane.showMessageDialog(this, "Medical Record number saved" + person.getMedical());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Medical Record number!Please enter a valid Medical Record number!.");
            
        }
        long health=Long.parseLong((thealth.getText()));
        if (health!=0L)
        {
            person.setHealth(health);
            JOptionPane.showMessageDialog(this, "Health plan beneficiary number saved" + person.getHealth());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Health plan beneficiary number!Please enter a valid Health plan beneficiary number!.");
            
        }
        double lat=Double.parseDouble(tlat.getText());
        if (lat!=0.0d)
        {
            person.setLatitude(lat);
            JOptionPane.showMessageDialog(this, "Latitude saved" + person.getLatitude());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Latitude number!Please enter a valid Latitude!.");
            
        }
        double lon=Double.parseDouble(tlon.getText());
        if (lon!=0.0d)
        {
            person.setLongitude(lon);
            JOptionPane.showMessageDialog(this, "Longitude saved" + person.getLongitude());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Longitude number!Please enter a valid Longitude!.");
            
        }
        short date=Short.parseShort(tdate.getText());
        if (date!=0 && (date>0 && date<32))
        {
            person.setDate(date);
            JOptionPane.showMessageDialog(this, "Date saved" + person.getDate());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Date!Please enter a valid Date!.");
            
        }
        short month=Short.parseShort(tmonth.getText());
        if (month!=0 && (month>0 && month<13))
        {
            person.setMonth(month);
            JOptionPane.showMessageDialog(this, "Month saved" + person.getMonth());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Month!Please enter a valid Month!.");
            
        }
        short year=Short.parseShort(tyear.getText());
        if (year!=0 && (year>=1000 && year<=2021))
        {
            person.setYear(year);
            JOptionPane.showMessageDialog(this, "Year saved" + person.getYear());
        } 
        else
        {
            fields=0;
            JOptionPane.showMessageDialog( this, "This is not a Year!Please enter a valid Year!.");
            
        }
        //
        //person.setUnique(tunique.getText());
        
        
        if(fields==1)
        {
            JOptionPane.showMessageDialog(this, "Person Information Saved!");   
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please check again and provide correct information! ");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tfaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaxActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void tssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tssnActionPerformed

    private void tlicenseplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlicenseplateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlicenseplateActionPerformed

    private void tdeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdeviceActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        int a=0;
        UploadJPanel pic = new UploadJPanel(person,a);
        
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnUploadBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadBioActionPerformed
        // TODO add your handling code here:
        int b=1;
        UploadJPanel pic = new UploadJPanel(person,b);
    }//GEN-LAST:event_btnUploadBioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel bio;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnUploadBio;
    private javax.swing.JLabel device;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fax;
    private javax.swing.JLabel geo;
    private javax.swing.JLabel health;
    private javax.swing.JLabel ip;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lat;
    private javax.swing.JLabel licenseno;
    private javax.swing.JLabel licenseplate;
    private javax.swing.JLabel linkedin;
    private javax.swing.JLabel lon;
    private javax.swing.JLabel medical;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField tbank;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tdevice;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfax;
    private javax.swing.JTextField thealth;
    private javax.swing.JTextField tip;
    private javax.swing.JTextField tlat;
    private javax.swing.JTextField tlicenseno;
    private javax.swing.JTextField tlicenseplate;
    private javax.swing.JTextField tlinkedin;
    private javax.swing.JTextField tlon;
    private javax.swing.JTextField tmedical;
    private javax.swing.JTextField tmonth;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tssn;
    private javax.swing.JTextField ttel;
    private javax.swing.JTextField tunique;
    private javax.swing.JTextField tyear;
    private javax.swing.JLabel unique;
    // End of variables declaration//GEN-END:variables
}
