/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author aamrah
 */
public class UploadJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UploadJPanel
     */
    Person person;
    File picture;
    int uploaded;
   
    public UploadJPanel(Person person, int a) {
        initComponents();
        this.person=person;
        JFileChooser chosenImg = new JFileChooser();
        //chosenImg.setFileFilter(new FileNameExtensionFilter(".jpeg"));
        //chosenImg.setFileHidingEnabled(false);
        //chosenImg.setFileSelectionMode( JFileChooser.FILES_AND_DIRECTORIES );
        uploaded =chosenImg.showOpenDialog(null);
        picture= chosenImg.getSelectedFile();
        String stri=chosenImg.getSelectedFile().getAbsolutePath();
        
        if (uploaded ==JFileChooser.APPROVE_OPTION)
        {
        //JOptionPane.showMessageDialog(this, "Image Uploaded from Location :" + picture);
        JOptionPane.showMessageDialog(this, "Image Uploaded from Location :" + stri);
        
        }
        else
        {
            JOptionPane.showMessageDialog(this, "ERROR!!!");
        }
        if(a==0)
        {
            this.person.setPhoto(stri);
        }
        else
        {
            this.person.setBio(stri);
        }    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
