/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author aamrah
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    String imgfile;
    String biofile;
    public ViewJPanel(Person person) {
        initComponents();
        this.person =person;
        displayPerson();
        
        imgfile= this.person.getPhoto();
        biofile=this.person.getBio();
        ImageIcon face = new ImageIcon(imgfile);
        Image face1= face.getImage();
        
        ImageIcon biometric = new ImageIcon(biofile);
        Image biometric1=biometric.getImage();
        
        bioimage.setIcon(biometric);
        
        image.setIcon(face);
        
        //photoframe.setFrameIcon(face);
        
        //photoframe.setSize(100, 100);
       
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tlicenseplate = new javax.swing.JTextField();
        health = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tdevice = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        ttel = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        tfax = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        tlinkedin = new javax.swing.JTextField();
        licenseno = new javax.swing.JLabel();
        tssn = new javax.swing.JTextField();
        fax = new javax.swing.JLabel();
        tip = new javax.swing.JTextField();
        tmedical = new javax.swing.JTextField();
        licenseplate = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        device = new javax.swing.JLabel();
        thealth = new javax.swing.JTextField();
        linkedin = new javax.swing.JLabel();
        ssn = new javax.swing.JLabel();
        tunique = new javax.swing.JTextField();
        tbank = new javax.swing.JTextField();
        ip = new javax.swing.JLabel();
        tlicenseno = new javax.swing.JTextField();
        medical = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        unique = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        tlon = new javax.swing.JTextField();
        geo1 = new javax.swing.JLabel();
        lon = new javax.swing.JLabel();
        lat = new javax.swing.JLabel();
        tlat = new javax.swing.JTextField();
        tmonth = new javax.swing.JTextField();
        tyear = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        bioimage = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        tlicenseplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlicenseplateActionPerformed(evt);
            }
        });

        health.setText("Health Plan beneficiary number");

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });

        tdevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeviceActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        label.setText("View");

        Name.setText("Name");

        tfax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaxActionPerformed(evt);
            }
        });

        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });

        dob.setText("Date of Birth (dd-mm-yyyy)");

        bank.setText("Bank account number");

        tel.setText("Telephone Number");

        licenseno.setText("Certificate/license number");

        tssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tssnActionPerformed(evt);
            }
        });

        fax.setText("Fax number");

        licenseplate.setText("License Plate Number");

        email.setText("Email ");

        device.setText("Device identifiers");

        linkedin.setText("LinkedIn");

        ssn.setText("SSN");

        ip.setText("Internet protocol address");

        medical.setText("Medical Record Number");

        photo.setText("Full face photo and Biometric");

        unique.setText("Any unique identifying number, characteristic, or cod");

        geo1.setText("Geographic data");

        lon.setText("Longitude");

        lat.setText("Latitude");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(health, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bank, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(licenseno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(licenseplate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(device, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(linkedin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(unique, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ip, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(medical, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(email)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photo)
                    .addComponent(geo1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tssn)
                            .addComponent(tmedical)
                            .addComponent(thealth)
                            .addComponent(tbank)
                            .addComponent(tlicenseno)
                            .addComponent(tlicenseplate)
                            .addComponent(tip)
                            .addComponent(tfax)
                            .addComponent(ttel)
                            .addComponent(tdevice)
                            .addComponent(tlinkedin)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(bioimage, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tunique)
                            .addComponent(tname)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lat)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(tyear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tlat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(lon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                        .addComponent(tlon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(photo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bioimage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dob)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lat)
                        .addComponent(lon))
                    .addComponent(geo1)
                    .addComponent(tlon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn)
                    .addComponent(tssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medical)
                    .addComponent(tmedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(health)
                    .addComponent(thealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bank)
                    .addComponent(tbank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseno)
                    .addComponent(tlicenseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseplate)
                    .addComponent(tlicenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(device)
                    .addComponent(tdevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkedin)
                    .addComponent(tlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ip)
                    .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel)
                    .addComponent(ttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fax)
                    .addComponent(tfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tunique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unique, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tlicenseplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlicenseplateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlicenseplateActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void tdeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdeviceActionPerformed

    private void tfaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaxActionPerformed

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tssnActionPerformed

    private void displayPerson() {
        //JOptionPane.showMessageDialog( this, person.getName());
        tname.setText(person.getName());
        temail.setText(person.getEmail());
        tssn.setText(String.valueOf(person.getSsn()));
        tlinkedin.setText(person.getLinkedin());
        tip.setText(person.getIp());
        ttel.setText(String.valueOf(person.getTelephone()));
        tfax.setText(String.valueOf(person.getFAX()));
        tdevice.setText(person.getDevice());
        tlicenseno.setText(person.getLicenseNo());
        tlicenseplate.setText(person.getLicensePlate());
        tbank.setText(String.valueOf(person.getBank()));
        tunique.setText(person.getUnique());
        thealth.setText(String.valueOf(person.getHealth()));
        tmedical.setText(String.valueOf(person.getMedical()));
        tlon.setText(String.valueOf(person.getLatitude()));
        tlat.setText(String.valueOf(person.getLongitude()));
        tdate.setText(String.valueOf(person.getDate()));
        tmonth.setText(String.valueOf(person.getMonth()));
        tyear.setText(String.valueOf(person.getYear()));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel bioimage;
    private javax.swing.JLabel device;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fax;
    private javax.swing.JLabel geo1;
    private javax.swing.JLabel health;
    private javax.swing.JLabel image;
    private javax.swing.JLabel ip;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lat;
    private javax.swing.JLabel licenseno;
    private javax.swing.JLabel licenseplate;
    private javax.swing.JLabel linkedin;
    private javax.swing.JLabel lon;
    private javax.swing.JLabel medical;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel ssn;
    private javax.swing.JTextField tbank;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tdevice;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tfax;
    private javax.swing.JTextField thealth;
    private javax.swing.JTextField tip;
    private javax.swing.JTextField tlat;
    private javax.swing.JTextField tlicenseno;
    private javax.swing.JTextField tlicenseplate;
    private javax.swing.JTextField tlinkedin;
    private javax.swing.JTextField tlon;
    private javax.swing.JTextField tmedical;
    private javax.swing.JTextField tmonth;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tssn;
    private javax.swing.JTextField ttel;
    private javax.swing.JTextField tunique;
    private javax.swing.JTextField tyear;
    private javax.swing.JLabel unique;
    // End of variables declaration//GEN-END:variables
}
