/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.LayoutManager;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import model.Car;
import model.Fleet;
import model.availableCars;

/**
 *
 * @author aamrah
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    public Fleet fleet, search;
    public int unique=0;
    
    public MainJFrame() throws FileNotFoundException, IOException {
        initComponents();
        
        workArea.setBackground(Color.BLACK);
        controlPanel.setBackground(Color.BLACK);
        fleet= new Fleet();
        
        this.importData();
       
    }
    
    public void importData() throws FileNotFoundException, IOException{
        
        
        String str="/Users/aamrah/NetBeansProjects/Assignment2/src/resources/DataFile.txt";
        //String file1 = "/Users/aamrah/Desktop/DataFile.txt";
        File file = new File(str);
        
        BufferedReader br
            = new BufferedReader(new FileReader(file));
 
        // Declaring loop variable
       String st;
        // Holds true till there is nothing to read
        while ((st = br.readLine()) != null){
           String[] s= st.split(",");
           Car c = new Car(unique++);
           
           c.setCompany(s[0]);
           c.setName(s[1]);
           c.setYear(Integer.parseInt(s[2]));
           c.setSerialNumber(Double.parseDouble(s[3]));
           c.setModelNumber(s[4]);
           c.setCity(s[5]);
           c.setCertificate(s[6]);
           c.setSeats(Integer.parseInt(s[7]));
           c.setIsAvailable(true);
           fleet.addCar(c);
           fleet.setCount(unique);
          
        }
     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblUber = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        btnPassenger = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workArea.setToolTipText("");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/map.jpeg"))); // NOI18N

        lblUber.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblUber.setForeground(new java.awt.Color(255, 255, 255));
        lblUber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUber.setText("UBER");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addGap(0, 181, Short.MAX_VALUE)
                .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );

        splitPane.setRightComponent(workArea);

        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPassenger.setText("Passenger");
        btnPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassengerActionPerformed(evt);
            }
        });
        controlPanel.add(btnPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 328, 180, -1));

        btnAdmin.setText("Administrator");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        controlPanel.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, 180, -1));

        splitPane.setLeftComponent(controlPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        AdminJPanel admin=new AdminJPanel(fleet,unique);
        admin.setBackground(Color.black);
        splitPane.setRightComponent(admin);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassengerActionPerformed
        // TODO add your handling code here:
        PassengerJPanel passenger=new PassengerJPanel(fleet, search);
        passenger.setBackground(Color.black);
        splitPane.setRightComponent(passenger);
        
    }//GEN-LAST:event_btnPassengerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnPassenger;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblUber;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
